### PR TITLE
Open bex 1007

### PR DESCRIPTION
**Pull request by travislbrundage**
## JIRA Ticket
[BEX-1007](https://issues.boundlessgeo.com:8443/browse/BEX-1007)

## Description
This is bringing over the PR from the previous exchange repo into the current one, as it was not previously merged.

Adds the `Content Manager` and `Content Creator` fields via the `ExchangeProfile` model. The "Content Manager" field determines if a user may register remote services. The "Content Creator" field determines if a user may upload documents or layers. `ExchangeProfile` has a one-to-one relationship to the `Profile` model from GeoNode, effectively extending it with these extra fields.

The templates and views have been updated to use these fields to prevent operations as necessary. The user is allowed to go to the view, but the buttons will be disabled, and `POST` requests ignored if the user does not have the correct permissions.

## TODO
- [ ] pycodestyle (`make lint`)
- [ ] tests (`make test`)

## Steps to Test or Reproduce
Exchange setup:
Run migrations. `docker-compose exec exchange /bin/bash` to enter the Exchange instance, then `python manage.py migrate` to run migrations.

Exchange testing:
1. Log in as `admin`
2. Navigate to the Django admin panel > Exchange Core > Exchange Profiles
3. Click on `test` to modify the `test` user. Deselect `Content Creator` and `Content Manager` and hit `Save`.
4. Log out of `admin` and log in to `test`.

Finally, try the following, and you should always be prevented via disabled buttons:
1. Data > Manage Remote Services
2. Manually navigate to `/services/register/` in the URL
3. Data > Create Layer
4. Data > Upload Layer
5. Data > Upload Document

## Setup Environment with PR

1. Cleanup previous state

```bash
make purge
```

2. Checkout PR

__Using git command (command line interface)__
```bash
pr_id=ADD_PR_NUMBER_HERE
git checkout master
git branch -D $pr_id
git fetch
git fetch origin pull/$pr_id/head:$pr_id
git checkout $pr_id
git submodule init
git submodule update --remote --recursive
```

__Using [Gitkraken](https://www.gitkraken.com/)__

+ In GitKraken, right click on the pull request you want to review. Select Add Remote and Checkout (the PR).

3. Start exchange

```bash
make start
```

4. Exchange Healthcheck

```bash
docker inspect --format '{{ .State.Health.Status }}' exchange
```

__NOTE:__ Only continue the following steps if the output from the above command is `healthy`. You may have to wait 
a few minutes.

---
@boundlessgeo/bex-qa

### CODE REVIEW

**Comment by travislbrundage** [comment]
A few things here:
1. For some reason this does not automatically create `ExchangeProfile` models for **new** Exchange instances. `Profile`s do get migrated properly _if_ they already exist. Any existing Exchange instances seem to migrate properly, but new instances don't capture the `admin` and `test` Profiles created by our fixtures; it seems as though the migrations run before they are installed. Not a big problem since it's only 2 profiles in that case, one of which we'll probably ignore, and they can still be updated manually.
2. We may want to skip over any staff users, as to me, it does not make sense to take these privileges away from a superuser. Besides, they could just go to the admin panel and give themselves those privileges right back.
3. Not sure I understand how to check the "License Compliance" CI that is currently failing? I'm guessing the problems are the `admin.py` and migration file lacking a license header, but I want to understand how to check what it says so I can be sure to correct it properly.
4. You can technically create more than one `ExchangeProfile` for each `Profile` object right now, due to it using a `ForeignKey`. I was instructed to probably do things this way, but I feel in this case a `OneToOne` relationship is more accurate. So I will probably update to use that.

**Comment by davisc** [comment]
@travislbrundage I agree with statement #4 regarding changing to a OneToOne relationship.

**Comment by davisc** [comment]
@travislbrundage Have you explored using the built-in groups to achieve the same result?

**Comment by travislbrundage** [comment]
We talked about this today, and I concur with Clarence's suggestion, it can be used for our desired purposes and avoids adding additional models that need to be configured in the admin panel, reducing potential confusion. I'll be closing this PR and opening a new one using the Groups concept already present within GeoNode.

**Pull request closed without merging**
