### PR TITLE
Update exchange for airgapped installs to remove links to boundlessge…

### PR DESCRIPTION
**Pull request by rcrissup**
Added new variable so that installs on closed networks will have the URL to boundlessgeo.com disabled

### CODE REVIEW

**Comment by amirahav** [comment]
My two suggestions of dealing with external links:

1. I think that in the case of a the link back to our homepage we could/should drop it instead of adding another config option to try on hide it.

2. If we don't want to go with the above, then adding a method to check internet connectivity and then hiding the link based on that would make more sense. 
We should generally attempt to have as little configuration options as possible to make it easier on our users.

**Comment by walker** [comment]
> If we don't want to go with the above, then adding a method to check internet connectivity and then hiding the link based on that would make more sense.

This might be preferred based on below.

> We should generally attempt to have as little configuration options as possible to make it easier on our users.

I appreciate this thought and agree.

**Comment by travislbrundage** [comment]
Just trying to generate a bit more literal direction here, should this be done in the view function and passed in through the context dict?

**Comment by walker** [comment]
@amirahav ^ see Travis' question.

**Comment by walker** [comment]
@rcrissup: based on discussion during standup:

1. Sticking with build/install configuration variable for this
2. Changing the configuration variable name to be more specific/self-descriptive
3. Looking to see documentation

**Comment by davisc** [comment]
@travislbrundage its being added to the scope via the context processor, is that what you are referring to?

**Comment by amirahav** [comment]
I think @travislbrundage question had more to do with my suggestion of creating a method to check network access.
But with @walker's comment above this is now pretty straight forward - replace ```ON_AIRGAPPED_NETWORK``` with something like ```SHOW_EXTERNAL_LINKS``` (or whatever) , and then see if there are other links that should be treated like this.

**Comment by walker** [comment]
Sorry @rcrissup, when the PR popped up in my feed, I didn't realize @arhote had already provided feedback on the getattr items. Didn't mean to double-team.

**Comment by arhote** [comment]
@davisc Any idea why this PR would be tanking the code coverage like that? He shouldn't have touched anything to make all those files go sideways.

**Pull request merged**
