### PR TITLE
Reference latest pycsw commit for CSW-T enhancements.

### PR DESCRIPTION
**Pull request by davisc**
Registry needs pycsw==2.1.dev for the CSW-T support.

### CODE REVIEW

**Comment by BerryDaniel** [comment]
@davisc @ingenieroariel can we get a tag created for https://github.com/geopython/pycsw/commit/4fc1fc1eee3ac4b83d2862d311b20efb142e13bd

and name it 1.0.1-registry

**Comment by davisc** [comment]
@BerryDaniel I updated the PR to include new registry and geonode versions.

**Comment by davisc** [comment]
The latest geonode breaks exchange.

**Comment by ingenieroariel** [comment]
You can use the following line for GeoNode: git+git://github.com/GeoNode/geonode.git@2.5.1#egg=geonode

**Pull request merged**
