### PR TITLE
Update quick copy link

### PR DESCRIPTION
**Pull request by davisc**
Link to WMS of uploaded GeoNode layer should copy specific reference

### CODE REVIEW

**Comment by amirahav** [comment]
Hold off on this, both the WMS and WFS and not correct.
WMS should be geoserver/{workspace}/{layer_name}/ows?service=wms&version=1.3.0&request=GetCapabilities

**Comment by arhote** [comment]
@amirahav Sorry, I didn't see your comment before I hit merge, I'll reopen and have @davisc Update.

**Comment by davisc** [comment]
@amirahav after thinking about it, if the layer is not public, GS will return unknown feature type.

**Comment by amirahav** [comment]
@davisc Right, but that would be the case for any layer specific request we make.
The layer must be public, or the request must include an access token.
Are you thinking we should just return the global getcaps instead of a layer specific one, just so the user doesn't see an error?

**Comment by amirahav** [comment]
Another option, which really don't like, would be to always allow gecaps on all services and layers, regardless of how exchange configures security.

This should work with Geofence, however will end up being very confusing for users.

**Pull request merged**
