### PR TITLE
update templates to support changes to remote services.

### PR DESCRIPTION
**Pull request by davisc**
This PR does the following:

1. Removes the templates/services directory
2. Updates the layer details page to support remote services.
screen shot 2018-01-16 at 12 23 28 pm

3. Allows all users to register remote services.
4. Updates the search card
screen shot 2018-01-16 at 12 16 08 pm

### CODE REVIEW

**Comment by bitner** [comment]
I'd love to see a unit test added on the exchange side for adding a service

**Comment by BablerR** [comment]
Testing #4 regarding the Updates to the Search Card and I am not seeing the related resources with the imported remote service.
The search card does not display WMS, WFS, KML or Mapserver

**Comment by davisc** [comment]
@BablerR regarding your comment above, looks like the links are being deleted when the layer is saved.

**Comment by davisc** [comment]
@BablerR item 4 has been fixed.

**Comment by BablerR** [comment]
Passes tests for the noted items in the PR.
A User with Active permissions is missing the Manage Menu to Edit Service Metadata, Scan for Resources and Remove Service

**Pull request merged**
