### PR TITLE
WIP-Adds django admin for csw record model and allows for simple harvesting.

### PR DESCRIPTION
**Pull request by davisc**
This PR adds the following capabilities in support of the content loading exercise:

**Django Admin for CSW Records Model**

- bulk command for sending records to registry
- allows categories to be assigned
screen shot 2017-04-09 at 4 17 26 pm

screen shot 2017-04-09 at 4 17 39 pm
screen shot 2017-04-09 at 4 53 12 pm

**Simple domain harvest for Superusers**

- Queries the ArcGIS Rest Api for supported layers
- Throttles processing load
- Enabled Admins to review the metadata prior to submitting to Registry
- Allows filtering by category, owner, relation, and status
- Modifies the field length for the abstract, creator, and title to accommodate more text.

screen shot 2017-04-09 at 4 17 11 pm

**Formatted the form using bootstrap form-control style class**

screen shot 2017-04-09 at 4 16 48 pm

### CODE REVIEW

**Comment by arhote** [comment]
My two cents:

* Basic Housekeeping
  * Comments would help improve the readability of the code, and make maintenance easier in the future. Especially in files like `exchange/core/utils.py`, `exchange/tasks.py`, and `exchange/templates/csw/new.html` which are where the bulk of the new features are added.
  * New features + decreased coverage is a bad combination. Adding some some tests would be cool so that we're sure everything is interacting the way we'd like.
* Is the intent for the `/csw/new` page meant to be that now, if you enter a url and click yes on the modal that appears you'll scrape the source for all layers that are available to you? 
  * If so, is it necessary to fill out all the following data fields? 
  * Or do you get redirected to a new page if you click yes? 
  * There might be some ambiguity here that could confuse the user depending on your answers to the above.

**Comment by BerryDaniel** [comment]
This needs some major refactoring and we need to identify requirements and unittests before merging is a consideration.

Some things to consider
- create a "Content Nomination" group that users must be added to to even access the CSW page
- add a full search, create, edit, delete functionality in the search. 
- add a django command to import "greedy" from a web service getcaps or esri

Just my thoughts

**Comment by davisc** [comment]
This PR was submitted to support this weeks  content loading exercise by super users who won't have access to a command line interface. Since the /csw form functionality was included as a MVP requirement not meant to be advertised, this applies to a limited user base for seeding registry with content in bulk. I will close this PR based on feedback, defer to changes in requirements, and advise this weeks system installers seed registry with bulk content as the capability will not exist in the UI.

**Comment by davisc** [comment]
Reopened. 

- Need to add migrations to change the field size constraints so that existing installs can be upgraded.
- Restrict `/csw/*` to admins and users in the data-manager group 
- Add a menu link under the user avatar dropdown with the label 'Registry' and links to '/csw/new'
- Change the label 'Creator' to 'Agency/Office' in the form html

**Pull request merged**
