### PR TITLE
Bump docker with hotfix and use 1.4.x docker branch for 1.4.x Exchange

### PR DESCRIPTION
**Pull request by travislbrundage**
## JIRA Ticket
N/A

## Description
We have a conflict with certain migrations and `loaddata resource_base`. At some point, some faulty migrations have been committed to either Exchange or GeoNode causing this problem. We can temporarily avert this with logic in the docker `entrypoint.sh`, which has been hotfixed and included. Long term, we need to correct the broken migrations.

The docker submodule has also been pointed to a new `1.4.x` branch for Exchange `master`, which is currently `1.4.x`. The changes on docker's `master` include updates relevant for Exchange `1.5.x`.

Note: We might consider doing a bump to Exchange `1.4.17` for this fix if the docker setup is important outside of our development.

## TODO
- [ ] pycodestyle (`make lint`)
- [ ] tests (`make test`)

## Steps to Test or Reproduce
You should see an error only on a **completely fresh build**. To do that, run `docker container prune && docker volume prune && docker image prune -a`. **WARNING - THIS WILL COMPLETELY WIPE ALL YOUR DOCKER CONTAINER IMAGES AND VOLUMES.** Normally you'd run `make purge` as instructed below, but in my experience that doesn't actually purge the volumes and images entirely. Manually remove the volumes & images for Exchange if you do not want to wipe all and `make purge` does not reproduce the errors.

Previously, you should see this error: https://gist.github.com/travislbrundage/82e92a749ece02e5ae85e63a3b45fa05

These changes should rectify the issue.

## Setup Environment with PR

1. Cleanup previous state

```bash
make purge
```

2. Checkout PR

__Using git command (command line interface)__
```bash
pr_id=ADD_PR_NUMBER_HERE
git checkout master
git branch -D $pr_id
git fetch
git fetch origin pull/$pr_id/head:$pr_id
git checkout $pr_id
git submodule init
git submodule update --remote --recursive
```

__Using [Gitkraken](https://www.gitkraken.com/)__

+ In GitKraken, right click on the pull request you want to review. Select Add Remote and Checkout (the PR).

3. Start exchange

```bash
make start
```

4. Exchange Healthcheck

```bash
docker inspect --format '{{ .State.Health.Status }}' exchange
```

__NOTE:__ Only continue the following steps if the output from the above command is `healthy`. You may have to wait 
a few minutes.

---
@boundlessgeo/bex-qa

### CODE REVIEW

**Comment by davisc** [comment]
@travislbrundage I will make a 1.4.x branch on Exchange

**Comment by travislbrundage** [comment]
:+1: Cool, just let me know and I'll PR to that instead.

**Comment by davisc** [comment]
https://github.com/boundlessgeo/exchange/tree/1.4.x

**Comment by travislbrundage** [comment]
Updated this PR for 1.4.x.

**Pull request merged**
