### PR TITLE
Use geoserver 2.12. docker image names

### PR DESCRIPTION
**Pull request by amirahav**
Uses GS 2.12. note - gs-geofence and geofence-server are somewhat problematic with the restlet to spring mvc refactoring done upstream. There are a couple of variables being set even though they shouldn't be.

Should replace https://github.com/boundlessgeo/exchange/pull/405 for container naming convention.
There is no need to push containers to quay before merging this pr.

Should be tested before merging.

### CODE REVIEW

**Comment by camerontesterman** [comment]
Tested this configuration. Unable to upload layers, tells me that the upload failed.

**Comment by amirahav** [comment]
@camerontesterman thank you for testing this!
It looks like there are a few other things that upstream broke, and ```/geoserver/rest``` is returning a 406.

**Comment by amirahav** [comment]
This should now work

**Comment by camerontesterman** [comment]
great thank you - in process of reviewing now

**Pull request merged**
