### PR TITLE
new pycsw security release

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by harts-boundless** [comment]
Hi, thank you very much for this PR! Would it be possible to pinpoint what change made from 2.0.1 to 2.0.2 was of interest here? We may need a little time to play with this but I personally think we should merge it soon.

**Comment by kalxas** [comment]
Hi @harts-boundless 
This is a security patch (CVE not publicly published yet, please contact me privately for more details, or contact @jodygarnett who received the e-mail from the security OSGeo mailing list)

**Comment by BerryDaniel** [comment]
@harts-boundless it looks like we have two options bump to 2.0.2 or update geonode to https://github.com/GeoNode/geonode/commit/5032500e6682cd918540008c3e3f43297895fefc for upstream to bump to that version. If the latter then we can remove this entry from the requirements.txt.

**Comment by harts-boundless** [comment]
If the GeoNode bump doesn't obviously break anything in Exchange then that solution is fine with me, we'll have to do it sometime. The question that I'm not in charge of is whether there are any imminent releases that would be messed up by this. Since - if at all possible - I'd prefer if we weren't forced to have a lot of changes on a release-specific branch and then have to merge those back into master later.

**Comment by kalxas** [comment]
The reason why I proposed this change on a released branch is the nature of the risk (security).
For master, I also think that upstream GeoNode will be the way to patch.

**Comment by harts-boundless** [comment]
@kalxas Sorry for any confusion here, but I'd like to clarify that I wasn't talking about your targeting of the PR there. I was just talking about trying to manage how much new divergence we create for the sake of releases in the near future. 

Since it comes up, though, I do think it would usually be most convenient for us if PRs are merged into master and then we are allowed to internally decide which instances of Exchange can upgrade to a newer tagged version and which need a cherry-pick... we aren't always fully at liberty to do whatever we want with every instance. I think we would all recognize the urgency of security patches, but updating the branch called "v1.0.2" may not achieve the desired outcome. So if you do not see an immediate merge here, please do not worry.

**Comment by kalxas** [comment]
Thank you. As long as the patch is applied, it is good for me :)

**Comment by harts-boundless** [comment]
We are now looking at a GeoNode bump in #96 but internally we can hotfix for pycsw as needed. I'm closing this in favor of #96, but THANKS for the report!

**Pull request closed without merging**
