### PR TITLE
[1.0.2] Switch to django-registry==0.3.11 and pycsw==2.0.1

### PR DESCRIPTION
**Pull request by ingenieroariel**
The main goal of this version is to support a CSW-T workflow, it has been tested with the RIO Foundation Layers from NGA while maintaining the ability to harvest records.

## Changelog

Version 0.3.11

 - Elasticsearch 1.7 compatibility.
 - CSW-T Insert support with custom <registry> tags.
 - Custom <registry> tags available in MapLoom UI.
 - Full screen MapLoom Registry modal.
 - Adaptive pagination based on available height.
 - Fixed MapProxy issues with WMS servers. workspace:name is now sent as layer name instead of name.
 - Fixed map display issues on hover for ArcGIS layers.
 - is_monitored is set to False on services uploaded via CSW-T.
 - Added users, admins and developers documentation.
 - More robust parsing of ArcGIS services url.
 - Switched to q.param and a.param instead of a_param and q_param for future compatibility with angular-search.
 - Added uuid field, requires migrations.

## Known Issues in version 0.3.11

 - Items from Brazil can appear in Australia: https://github.com/cga-harvard/HHypermap/issues/199
 - Service name is not set up properly when ingesting via CSW-T: https://github.com/cga-harvard/HHypermap/issues/200
 - Some bounding boxes are advertised as EPSG:4326 but have values in an invalid range: https://github.com/cga-harvard/HHypermap/issues/192
 - Service and Layer checks can cause overload on remote servers. Checks should not be so exhaustive. https://github.com/cga-harvard/HHypermap/issues/173
 - Last check date is not being reported, last modification date is being reported instead. https://github.com/cga-harvard/HHypermap/issues/201
 - Sibling services are being imported in ArcGIS services: https://github.com/cga-harvard/HHypermap/issues/203

## Notes

This should be pulled with a MapLoom version that contains this change: https://github.com/boundlessgeo/MapLoom/pull/32

### CODE REVIEW

**Comment by BerryDaniel** [comment]
@ingenieroariel @JorgeMartinezG wasnt there additional upgrades that needed to be applied.

@davisc SHould we hold off on merging this, since the next release was going to separate the two projects.

**Comment by ingenieroariel** [comment]
This has the latest.

There is a new elasticsearch 1.7 version of registry 0.3.10 but that should
not be a blocker for this.

If you are cutting a release it is better to do it with the 0.3.10  version
than the 0.3.6.

When 0.3.11 is released I will create another PR

**Comment by BerryDaniel** [comment]
@cdavis @hemphillda This has been tested on customer env, no issues were identified.

**Comment by BerryDaniel** [comment]
@ingenieroariel I have created a branch called v1.0.2 can modify this pull request to use that branch. The reason for this is we still need a version of what we just released, but after this release v1.1.0 we will be separating the two applications.

**Pull request merged**
