### PR TITLE
removal of registry from exchange.

### PR DESCRIPTION
**Pull request by BerryDaniel**

### CODE REVIEW

**Comment by harts-boundless** [comment]
I like it. It will simplify Exchange. The PR itself is pretty clean. There are no added dependencies or migrations. Exchange is starting fine and in broad strokes appears to work.

In manual testing, I'm finding that I cannot add layers to a map. 

(Front page) -> Upload -> Browse -> (Add shapefile files and hit OK) -> Upload Files -> wait; Layer Info -> Create a Map -->
-- although I created the map from the layer info page, worldwide basemap is seen fully zoomed out, the only item under Layers is OpenStreetMap. No other indication there was an error.
Uploaded layer visible in http://172.16.238.2/layers/?limit=100&offset=0

Click + for "Add Layer", modal pops up. No layers seen to add. Same situation if one uploads a layer, then goes to Maps and creates a new map and attempts to add a layer. No layers seen to add.

**Comment by BerryDaniel** [comment]
@harts-boundless is this using vagrant or docker?

**Comment by harts-boundless** [comment]
Confirm same behavior in the Vagrant env (after resolving a problem with vagrant itself)

**Comment by harts-boundless** [comment]
In the state that isn't working on this PR, the "Add Layers" modal shows "Connected as anonymous." Below that, no layers. There is a button "Fetch Layers from Server" with a tooltip "This server is configured to lazily load layers."

In the state that is working on master, "Connected as admin." Below that a list of layers. No button for fetching layers from server. There is a request to wms?SERVICE=WMS&REQUEST=GetCapabilities that seems to contain the used info

**Comment by harts-boundless** [comment]
So, the removal of the upload selenium test in Travis CI (it is failing due to some geoserver deployment issue in Travis CI) is one issue.

However, I'm still seeing problems on this branch that would personally make me hesitant to merge.

To start with, there is still the Registry button in MapLoom (which would be ok, except the shipping configuration doesn't seem to have a Registry in it, so maybe this should be conditionally suppressed, or we should change the default dev config to have a standalone Registry in it).

oct20_1

Of course, when you use this Registry button, there are no catalogs and the GUI doesn't make much sense

oct20_2

The already mentioned issue about uploaded layers not appearing here still applies - this is after uploading san_andres_y_providencia_administrative and verifying it exists in the layers list; note that all MapLoom has is the basemap:

oct20_3

And as before, the (non-registry) add layers modal doesn't list anything, and searching in it doesn't do anything

oct20_4

**Comment by BerryDaniel** [comment]
@cdavis it is ready for your maploom update

**Comment by harts-boundless** [comment]
There are a few git issues, which I would be happy to help more with if desired

The docs update commit either needs to be briefly annotated as to how it relates to registry removal, or moved out to another PR if it doesn't relate.

When trying to rebase this (5908181e81d2502a0f3083481a4c86ce9e291bd3) onto master (54c50942239b28d9cb3371ceb773dee58f81c2cd), I see at least one merge conflict. I'm not really sure why GitHub says it will merge cleanly.

This could use some squash cleanup.
1. There are a bunch of apparently duplicated commits
2. To keep history cleaner on master, we could squash out merge commits like 07cd2735626cf7a9e58a2022e43dbace09a7f958 caef73bc4acb072e5d556daf2607b0e3685f9af1 f7d7cb691fb932489763bc64ffd1ef2253229511 569f2fe65cfbf4d2d7f4cac6e2eeeb34cdc17336

**Comment by BerryDaniel** [comment]
The docs update commit was originally (801c65ba57915eea2be8a48c46456d3331bc27fe) on master branch and looks like on the registry branch it was removed on this commit (12a7742c142dc9d51068794a1269f8144cda2e47).  This is a mess any help @harts-boundless would be appreciated.

**Comment by harts-boundless** [comment]
After a cleanup (hope it's OK that my commits squashed into Dan or Clarence commits) I'm happy with how this looks in git.

The Maploom issue also seems to have gone away as you would expect.

LGTM

**Comment by sarasafavi** [comment]
Tested locally, seems fine to me

**Pull request merged**
